apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    service: backend-feed
